:sparkles: add support for cropper v1
mindee/mindee-api-java pull request #120
Opened 2023-09-06 16:43 UTC by ianardee

## Description
autogenerated

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires a change to the official Guide documentation.

2023-09-06 16:53 UTC, sebastianMindee requested changes
I think some auto-generated code should be removed for empty docs.

2023-09-06 16:53 UTC, sebastianMindee commented on src/main/java/com/mindee/product/cropper/CropperV1Document.java
> +}
Mmmh no.

2023-09-06 16:53 UTC, sebastianMindee commented on docs/code_samples/cropper_v1.txt
> +//    System.out.println(response.getDocument().getInference().getPrediction().toString());
Literally impossible :upside_down_face:

2023-09-07 10:34 UTC, ianardee commented on src/main/java/com/mindee/product/cropper/CropperV1Document.java
> +}
done

2023-09-07 10:34 UTC, ianardee commented on docs/code_samples/cropper_v1.txt
> +//    System.out.println(response.getDocument().getInference().getPrediction().toString());
removed

2023-09-07 12:16 UTC, sebastianMindee commented on src/main/java/com/mindee/product/cropper/CropperV1Document.java
> +}
:grin:

2023-09-07 12:19 UTC, merged